### ISSUE TITLE
Ruby

### ISSUE THREAD

**Issue by ryanboydguam** [exbitron/api#2]
require 'openssl'

nonce = (Time.now.to_f.round(3)*1000).to_i
api_key = '*****'
secret = '*****'
OpenSSL::HMAC.hexdigest("SHA256", secret, nonce + api_key)

This needs to be changed to 
require 'openssl'

nonce = (Time.now.to_f.round(3)*1000).to_i
api_key = '*****'
secret = '*****'
OpenSSL::HMAC.hexdigest("SHA256", secret, nonce.to_s + api_key)

ruby will not automatically turn an integer to a string when called like this

**Comment by arzzen** [comment]
fixed
